services:
  db:
    image: postgres:16-alpine
    restart: unless-stopped
    environment:
      POSTGRES_USER: winrace
      POSTGRES_PASSWORD: winrace
      POSTGRES_DB: winrace
    ports:
      - "5432:5432"
    volumes:
      - winrace_db_data:/var/lib/postgresql/data

volumes:
  winrace_db_data:
