import {
  Activity,
  AlertTriangle,
  ArrowDown,
  ArrowRight,
  ArrowUp,
  Bath,
  Battery,
  BatteryCharging,
  Bed,
  Bell,
  BellOff,
  Briefcase,
  Camera,
  Check,
  CheckCircle2,
  ChevronDown,
  ChevronLeft,
  ChevronRight,
  ChevronUp,
  Clock,
  Cloud,
  CloudLightning,
  CloudMoon,
  CloudRain,
  CloudSnow,
  CookingPot,
  DoorClosed,
  DoorOpen,
  Download,
  Droplet,
  Droplets,
  Filter,
  Flame,
  Gauge,
  Globe,
  Grid3x3,
  HelpCircle,
  Home,
  KeyRound,
  Lamp,
  LayoutGrid,
  Leaf,
  Lightbulb,
  Loader2,
  Lock,
  LogOut,
  Microwave,
  Minus,
  Monitor,
  Moon,
  MoreHorizontal,
  Pencil,
  Plug,
  PlugZap,
  Plus,
  Power,
  PowerOff,
  Refrigerator,
  RotateCcw,
  Router,
  Save,
  Search,
  Server,
  Settings,
  Shield,
  ShieldAlert,
  ShieldCheck,
  Siren,
  Sliders,
  Snowflake,
  Sofa,
  Sun,
  Sunrise,
  Thermometer,
  Timer,
  Trash2,
  TrendingDown,
  TrendingUp,
  Undo2,
  User,
  Warehouse,
  WashingMachine,
  Wifi,
  WifiOff,
  Wind,
  Workflow,
  X,
  Zap,
  ZapOff,
  type LucideIcon,
  type LucideProps,
} from "lucide-react";

const ICONS: Record<string, LucideIcon> = {
  activity: Activity,
  "alert-triangle": AlertTriangle,
  "arrow-down": ArrowDown,
  "arrow-right": ArrowRight,
  "arrow-up": ArrowUp,
  bath: Bath,
  battery: Battery,
  "battery-charging": BatteryCharging,
  bed: Bed,
  bell: Bell,
  "bell-off": BellOff,
  briefcase: Briefcase,
  camera: Camera,
  check: Check,
  "check-circle": CheckCircle2,
  "chevron-down": ChevronDown,
  "chevron-left": ChevronLeft,
  "chevron-right": ChevronRight,
  "chevron-up": ChevronUp,
  clock: Clock,
  "door-closed": DoorClosed,
  cloud: Cloud,
  "cloud-lightning": CloudLightning,
  "cloud-moon": CloudMoon,
  "cloud-rain": CloudRain,
  "cloud-snow": CloudSnow,
  "cooking-pot": CookingPot,
  download: Download,
  droplet: Droplet,
  droplets: Droplets,
  filter: Filter,
  flame: Flame,
  gauge: Gauge,
  globe: Globe,
  grid: Grid3x3,
  home: Home,
  key: KeyRound,
  lamp: Lamp,
  "layout-grid": LayoutGrid,
  leaf: Leaf,
  lightbulb: Lightbulb,
  loader: Loader2,
  lock: Lock,
  "log-out": LogOut,
  microwave: Microwave,
  minus: Minus,
  monitor: Monitor,
  moon: Moon,
  "more-horizontal": MoreHorizontal,
  pencil: Pencil,
  plug: Plug,
  "plug-zap": PlugZap,
  plus: Plus,
  power: Power,
  "power-off": PowerOff,
  refrigerator: Refrigerator,
  "rotate-ccw": RotateCcw,
  router: Router,
  save: Save,
  search: Search,
  server: Server,
  settings: Settings,
  shield: Shield,
  "shield-alert": ShieldAlert,
  "shield-check": ShieldCheck,
  siren: Siren,
  sliders: Sliders,
  snowflake: Snowflake,
  sofa: Sofa,
  sun: Sun,
  sunrise: Sunrise,
  thermometer: Thermometer,
  timer: Timer,
  trash: Trash2,
  "trending-down": TrendingDown,
  "trending-up": TrendingUp,
  undo: Undo2,
  user: User,
  warehouse: Warehouse,
  "washing-machine": WashingMachine,
  wifi: Wifi,
  "wifi-off": WifiOff,
  wind: Wind,
  workflow: Workflow,
  x: X,
  zap: Zap,
  "zap-off": ZapOff,
  "door-open": DoorOpen,
};

export interface IconProps extends Omit<LucideProps, "ref"> {
  name: string;
}

export function Icon({ name, ...props }: IconProps) {
  const Component = ICONS[name] ?? HelpCircle;
  return <Component {...props} />;
}
