// Fehlercodes → verständliche Beschreibung und konkrete nächste Handlung.
import { getLang } from "./i18n";

type Entry = { title: string; action: string };

const DE: Record<string, Entry> = {
  network: { title: "Keine Verbindung zum Dienst", action: "Internetverbindung prüfen. ON AIR versucht es automatisch erneut – Anmeldung bleibt erhalten." },
  server_error: { title: "Störung beim Anbieter", action: "Meist vorübergehend. ON AIR wiederholt begrenzt und automatisch." },
  rate_limited: { title: "Zu viele Anfragen", action: "Kurz warten – ON AIR hält die vom Anbieter verlangte Pause ein." },
  quota_exhausted: { title: "API-Kontingent erschöpft", action: "Abfragen sind ausgesetzt. Später erneut prüfen oder Abfrage-Intervall erhöhen." },
  suspended: { title: "Vorübergehend ausgesetzt", action: "ON AIR pausiert Anfragen und fährt automatisch fort." },
  forbidden: { title: "Zugriff verweigert", action: "Berechtigungen, Kontovoraussetzungen und App-Zugang in der Diagnose prüfen." },
  user_not_registered: { title: "Konto nicht freigeschaltet", action: "Im Spotify Developer Dashboard unter „User Management“ dein Spotify-Konto eintragen." },
  premium_required: { title: "Spotify Premium erforderlich", action: "Wiedergabesteuerung und Queue erfordern Spotify Premium." },
  no_active_device: { title: "Kein aktives Wiedergabegerät", action: "Spotify öffnen und einen Song starten, dann erneut versuchen." },
  not_found: { title: "Nicht gefunden", action: "Eingabe prüfen oder anders suchen." },
  reauth_required: { title: "Anmeldung abgelaufen", action: "Erneut anmelden. Warteschlange und Einstellungen bleiben erhalten." },
  not_signed_in: { title: "Nicht angemeldet", action: "Unter Einstellungen → Verbindungen anmelden." },
  unauthorized: { title: "Anmeldung abgelehnt", action: "Erneut anmelden; hilft das nicht, Client-ID prüfen." },
  session_ended: { title: "Vorgang abgebrochen", action: "Die Sitzung wurde beendet. Bei Bedarf erneut anmelden." },
  bad_request: { title: "Anfrage abgelehnt", action: "Technische Details prüfen." },
  decode: { title: "Unerwartete Antwort", action: "Erneut versuchen; bei Wiederholung Diagnosebericht erstellen." },
  config: { title: "Konfiguration fehlt oder ist ungültig", action: "Client-ID in den Einstellungen prüfen." },
  missing_client_id: { title: "Client-ID fehlt", action: "Eigene Developer-App anlegen und Client-ID eintragen." },
  missing_scope: { title: "Berechtigung fehlt", action: "Abmelden und erneut anmelden, damit alle benötigten Rechte erteilt werden." },
  missing_scope_or_permission: { title: "Berechtigung fehlt", action: "Abmelden und erneut anmelden, damit alle benötigten Rechte erteilt werden." },
  port_in_use: { title: "Anmelde-Port belegt", action: "Anderes Programm schließen oder in den Einstellungen einen anderen Port wählen – dann die Redirect-URI in der Spotify-App anpassen." },
  login_timeout: { title: "Anmeldung nicht abgeschlossen", action: "Erneut starten und im Browser bestätigen." },
  login_cancelled: { title: "Anmeldung abgebrochen", action: "Bei Bedarf erneut starten." },
  login_denied: { title: "Zugriff im Browser abgelehnt", action: "Erneut starten und „Zustimmen“ wählen." },
  state_mismatch: { title: "Ungültige Anmeldeantwort", action: "Anmeldung in ON AIR neu starten und alte Browser-Tabs schließen." },
  token_exchange: { title: "Anmeldung fehlgeschlagen", action: "Redirect-URI in der Spotify-App exakt wie angezeigt eintragen und erneut versuchen." },
  login_failed: { title: "Anmeldung fehlgeschlagen", action: "Technische Details prüfen und erneut versuchen." },
  refresh_token_expiring: { title: "Anmeldung läuft bald ab", action: "Spotify verlangt nach rund 6 Monaten eine neue Anmeldung. Am besten vor dem nächsten Stream neu anmelden." },
  overlay_port: { title: "Overlay-Server nicht gestartet", action: "Port ist belegt. Unter Widgets einen anderen Port wählen." },
  file_dir_missing: { title: "Ordner nicht gefunden", action: "Anderen Speicherort für die Textdatei wählen." },
  reconnecting: { title: "Verbindung wird wiederhergestellt", action: "Automatisch – kein Eingriff nötig." },
  connecting: { title: "Verbindet", action: "Einen Moment." },
  disabled: { title: "Nicht aktiv", action: "Optional: Twitch unter Einstellungen verbinden." },
  access_denied: { title: "Zugriff abgelehnt", action: "Erneut starten und bei Twitch bestätigen." },
  error: { title: "Fehler", action: "Technische Details prüfen." },
  ok: { title: "OK", action: "" },
};

const EN: Record<string, Entry> = {
  network: { title: "No connection to the service", action: "Check your internet connection. ON AIR retries automatically – you stay signed in." },
  server_error: { title: "Provider outage", action: "Usually temporary. ON AIR retries automatically, with limits." },
  rate_limited: { title: "Too many requests", action: "Wait briefly – ON AIR observes the pause required by the provider." },
  quota_exhausted: { title: "API quota exhausted", action: "Requests are suspended. Check again later or increase the polling interval." },
  suspended: { title: "Temporarily suspended", action: "ON AIR pauses requests and continues automatically." },
  forbidden: { title: "Access denied", action: "Check permissions, account requirements and app access in diagnostics." },
  user_not_registered: { title: "Account not allow-listed", action: "Add your Spotify account under “User Management” in the Spotify Developer Dashboard." },
  premium_required: { title: "Spotify Premium required", action: "Playback control and queue require Spotify Premium." },
  no_active_device: { title: "No active playback device", action: "Open Spotify and start a song, then try again." },
  not_found: { title: "Not found", action: "Check your input or search differently." },
  reauth_required: { title: "Sign-in expired", action: "Sign in again. Queue and settings are kept." },
  not_signed_in: { title: "Not signed in", action: "Sign in under Settings → Connections." },
  unauthorized: { title: "Sign-in rejected", action: "Sign in again; if that fails, check the client ID." },
  session_ended: { title: "Operation cancelled", action: "The session was ended. Sign in again if needed." },
  bad_request: { title: "Request rejected", action: "Check the technical details." },
  decode: { title: "Unexpected response", action: "Try again; if it repeats, create a diagnostics report." },
  config: { title: "Configuration missing or invalid", action: "Check the client ID in settings." },
  missing_client_id: { title: "Client ID missing", action: "Create your own developer app and enter its client ID." },
  missing_scope: { title: "Permission missing", action: "Sign out and in again so all required permissions are granted." },
  missing_scope_or_permission: { title: "Permission missing", action: "Sign out and in again so all required permissions are granted." },
  port_in_use: { title: "Sign-in port in use", action: "Close the other program or choose another port in settings – then update the redirect URI in the Spotify app." },
  login_timeout: { title: "Sign-in not completed", action: "Start again and confirm in the browser." },
  login_cancelled: { title: "Sign-in cancelled", action: "Start again if needed." },
  login_denied: { title: "Access denied in browser", action: "Start again and choose “Agree”." },
  state_mismatch: { title: "Invalid sign-in response", action: "Restart sign-in in ON AIR and close old browser tabs." },
  token_exchange: { title: "Sign-in failed", action: "Enter the redirect URI exactly as shown in the Spotify app and try again." },
  login_failed: { title: "Sign-in failed", action: "Check the technical details and try again." },
  refresh_token_expiring: { title: "Sign-in expires soon", action: "Spotify requires a new sign-in after about 6 months. Best sign in again before your next stream." },
  overlay_port: { title: "Overlay server not started", action: "The port is in use. Choose another port under Widgets." },
  file_dir_missing: { title: "Folder not found", action: "Choose another location for the text file." },
  reconnecting: { title: "Reconnecting", action: "Automatic – no action needed." },
  connecting: { title: "Connecting", action: "One moment." },
  disabled: { title: "Not active", action: "Optional: connect Twitch in settings." },
  access_denied: { title: "Access denied", action: "Start again and confirm on Twitch." },
  error: { title: "Error", action: "Check the technical details." },
  ok: { title: "OK", action: "" },
};

export function describeError(code: string): Entry {
  const dict = getLang() === "en" ? EN : DE;
  return dict[code] ?? dict.error;
}
